In [3]:
import numpy as np
import pandas as pd

# NUMPY Methods

In [18]:
##Creating an array
list = [23, 26, 19, 31, 22, 27]
a = np.array(list)
a

array([23, 26, 19, 31, 22, 27])

In [7]:
##average
np.average(a)

24.666666666666668

In [29]:
##arange
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
##reshape
b= b.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
##max
a.max()

31

In [12]:
##min
a.min()

19

In [19]:
##greater
np.greater(a,np.arange(21,27))

array([ True,  True, False,  True, False,  True])

In [44]:
##zeros
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [45]:
##ones
o = np.ones((2,2))
o

array([[1., 1.],
       [1., 1.]])

In [47]:
##concatenate
np.concatenate((z,o), axis = 0)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [50]:
##diagonal
b.diagonal()

array([1, 5, 9])

In [52]:
##delete
np.delete(b, 1, 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [55]:
##insert
np.insert(b, 1 , (22,19, 17), axis=0 )

array([[ 1,  2,  3],
       [22, 19, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# PANDAS Methods

In [63]:
##Series
list = np.array(np.arange(10,15))
pd.Series(list)

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [68]:
##DataFrame
dic = {'Name': ['Ajannu', 'Justina', 'Adegoke', 'Ciroma'], 'Age' : [21, 25, 28, 36], 'Location': ['Kwara', 'Enugu', 'Oyo', 'Adamawa']}
pf = pd.DataFrame(dic)
pf

Name  Age Location
0   Ajannu   21    Kwara
1  Justina   25    Enugu
2  Adegoke   28      Oyo
3   Ciroma   36  Adamawa

In [93]:
##Count
pf.count()

Name        4
Age         4
Location    4
dtype: int64

In [104]:
##Describe
pf.describe()

Age
count   4.000000
mean   27.500000
std     6.350853
min    21.000000
25%    24.000000
50%    26.500000
75%    30.000000
max    36.000000

In [96]:
##Max
pf['Age'].max()

36

In [98]:
##Min
pf['Age'].min()

21

In [92]:
##Loc
pf.loc[0:3]

Name  Age Location
0   Ajannu   21    Kwara
1  Justina   25    Enugu
2  Adegoke   28      Oyo
3   Ciroma   36  Adamawa

In [91]:
##iloc
pf.iloc[0:3]

Name  Age Location
0   Ajannu   21    Kwara
1  Justina   25    Enugu
2  Adegoke   28      Oyo

In [100]:
##where
pf.where(pf['Age']>25)

Name   Age Location
0      NaN   NaN      NaN
1      NaN   NaN      NaN
2  Adegoke  28.0      Oyo
3   Ciroma  36.0  Adamawa

In [102]:
##get
pf.get('Name')

0     Ajannu
1    Justina
2    Adegoke
3     Ciroma
Name: Name, dtype: object

In [108]:
##head
pf.head(2)

Name  Age Location
0   Ajannu   21    Kwara
1  Justina   25    Enugu

In [107]:
##tail
pf.tail(2)

Name  Age Location
2  Adegoke   28      Oyo
3   Ciroma   36  Adamawa

In [110]:
##Memory usage
pf.memory_usage(deep = True)

Index       128
Name        254
Age          32
Location    248
dtype: int64

In [111]:
##Value Counts
pf['Location'].value_counts()

Oyo        1
Enugu      1
Kwara      1
Adamawa    1
Name: Location, dtype: int64

In [115]:
##groupby
pf.groupby(by = 'Name').Age.mean()

Name
Adegoke    28
Ajannu     21
Ciroma     36
Justina    25
Name: Age, dtype: int64

In [118]:
##sortvalues
pf.sort_values(by = 'Name', inplace = True)
pf

Name  Age Location
2  Adegoke   28      Oyo
0   Ajannu   21    Kwara
3   Ciroma   36  Adamawa
1  Justina   25    Enugu